In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [37]:
# Import the OCV curve from the data analysis laboratory

input_gen = "/Users/mac/Desktop/ RED/Data Final Project/AGGREGATED_GENERATION_PER_TYPE_GENERATION_202312312300-202412312300.xlsx"  # Load the Excel file
input_price = "/Users/mac/Desktop/ RED/Data Final Project/GUI_ENERGY_PRICES_202412222300-202412232300.xlsx"  # Load the Excel file
input_tload = "/Users/mac/Desktop/ RED/Data Final Project/GUI_TOTAL_LOAD_DAYAHEAD_202312312300-202412312300.xlsx"  # Load the Excel file
input_load = "/Users/mac/Desktop/ RED/Data Final Project/Total Load - Day Ahead _ Actual_202401010000-202501010000.xlsx"  # Load the Excel file


df_gen= pd.read_excel(input_gen)  # Read the data into a Pandas DataFrame
df_price= pd.read_excel(input_price)
df_load= pd.read_excel(input_load)
df_load_ahead= pd.read_excel(input_tload)
#SOC_curve = data["SOC"].to_numpy()  # Convert the columns to NumPy arrays
#V0_curve = data["OCV"].to_numpy()

In [31]:
df_load_ahead.head(50)

,Total Load - Day-ahead / Actual,Unnamed: 1,Unnamed: 2
0,Day-ahead Total Load Forecast [6.1.B],NaN,NaN
1,Actual Total Load [6.1.A],NaN,NaN
2,01/01/2024 00:00 - 01/01/2025 00:00 (CET/CEST),NaN,NaN
3,NaN,NaN,NaN
4,01/01/2024 00:00:00 - 01/01/2025 00:00:00,NaN,NaN
5,MTU,BZN|ES,NaN
6,NaN,Day-ahead Total Load Forecast,Actual total load
7,NaN,[MW],[MW]
8,01/01/2024 00:00:00 - 01/01/2024 00:15:00,21981.00,22460.00
9,01/01/2024 00:15:00 - 01/01/2024 00:30:00,21863.00,22060.00
10,01/01/2024 00:30:00 - 01/01/2024 00:45:00,21807.00,21880.00
11,01/01/2024 00:45:00 - 01/01/2024 01:00:00,21767.00,21788.00
12,01/01/2024 01:00:00 - 01/01/2024 01:15:00,21890.00,21648.00
13,01/01/2024 01:15:00 - 01/01/2024 01:30:00,21715.00,21508.00
14,01/01/2024 01:30:00 - 01/01/2024 01:45:00,21410.00,21312.00
15,01/01/2024 01:45:00 - 01/01/2024 02:00:00,21012.00,21044.00
16,01/01/2024 02:00:00 - 01/01/2024 02:15:00,20525.00,20748.00
17,01/01/2024 02:15:00 - 01/01/2024 02:30:00,20113.00,20416.00
18,01/01/2024 02:30:00 - 01/01/2024 02:45:00,19766.00,20144.00
19,01/01/2024 02:45:00 - 01/01/2024 03:00:00,19479.00,19836.00
20,01/01/2024 03:00:00 - 01/01/2024 03:15:00,19202.00,19520.00
21,01/01/2024 03:15:00 - 01/01/2024 03:30:00,18976.00,19192.00
22,01/01/2024 03:30:00 - 01/01/2024 03:45:00,18757.00,18900.00
23,01/01/2024 03:45:00 - 01/01/2024 04:00:00,18548.00,18684.00
24,01/01/2024 04:00:00 - 01/01/2024 04:15:00,18301.00,18500.00
25,01/01/2024 04:15:00 - 01/01/2024 04:30:00,18140.00,18336.00
26,01/01/2024 04:30:00 - 01/01/2024 04:45:00,18013.00,18172.00
27,01/01/2024 04:45:00 - 01/01/2024 05:00:00,17927.00,18036.00
28,01/01/2024 05:00:00 - 01/01/2024 05:15:00,17792.00,17908.00
29,01/01/2024 05:15:00 - 01/01/2024 05:30:00,17797.00,17948.00
30,01/01/2024 05:30:00 - 01/01/2024 05:45:00,17850.00,17888.00
31,01/01/2024 05:45:00 - 01/01/2024 06:00:00,17941.00,17852.00
32,01/01/2024 06:00:00 - 01/01/2024 06:15:00,18044.00,17824.00
33,01/01/2024 06:15:00 - 01/01/2024 06:30:00,18177.00,17988.00
34,01/01/2024 06:30:00 - 01/01/2024 06:45:00,18311.00,18048.00
35,01/01/2024 06:45:00 - 01/01/2024 07:00:00,18435.00,18108.00
36,01/01/2024 07:00:00 - 01/01/2024 07:15:00,18606.00,18176.00
37,01/01/2024 07:15:00 - 01/01/2024 07:30:00,18673.00,18344.00
38,01/01/2024 07:30:00 - 01/01/2024 07:45:00,18698.00,18420.00
39,01/01/2024 07:45:00 - 01/01/2024 08:00:00,18701.00,18512.00
40,01/01/2024 08:00:00 - 01/01/2024 08:15:00,18643.00,18552.00
41,01/01/2024 08:15:00 - 01/01/2024 08:30:00,18672.00,18548.00
42,01/01/2024 08:30:00 - 01/01/2024 08:45:00,18747.00,18464.00
43,01/01/2024 08:45:00 - 01/01/2024 09:00:00,18862.00,18344.00
44,01/01/2024 09:00:00 - 01/01/2024 09:15:00,18972.00,18312.00
45,01/01/2024 09:15:00 - 01/01/2024 09:30:00,19140.00,18504.00
46,01/01/2024 09:30:00 - 01/01/2024 09:45:00,19321.00,18712.00
47,01/01/2024 09:45:00 - 01/01/2024 10:00:00,19511.00,18856.00
48,01/01/2024 10:00:00 - 01/01/2024 10:15:00,19712.00,19028.00
49,01/01/2024 10:15:00 - 01/01/2024 10:30:00,19911.00,19220.00

In [33]:
df_load_ahead.head(50)

,Total Load - Day-ahead / Actual,Unnamed: 1,Unnamed: 2
0,Day-ahead Total Load Forecast [6.1.B],NaN,NaN
1,Actual Total Load [6.1.A],NaN,NaN
2,01/01/2024 00:00 - 01/01/2025 00:00 (CET/CEST),NaN,NaN
3,NaN,NaN,NaN
4,01/01/2024 00:00:00 - 01/01/2025 00:00:00,NaN,NaN
5,MTU,BZN|ES,NaN
6,NaN,Day-ahead Total Load Forecast,Actual total load
7,NaN,[MW],[MW]
8,01/01/2024 00:00:00 - 01/01/2024 00:15:00,21981.00,22460.00
9,01/01/2024 00:15:00 - 01/01/2024 00:30:00,21863.00,22060.00
10,01/01/2024 00:30:00 - 01/01/2024 00:45:00,21807.00,21880.00
11,01/01/2024 00:45:00 - 01/01/2024 01:00:00,21767.00,21788.00
12,01/01/2024 01:00:00 - 01/01/2024 01:15:00,21890.00,21648.00
13,01/01/2024 01:15:00 - 01/01/2024 01:30:00,21715.00,21508.00
14,01/01/2024 01:30:00 - 01/01/2024 01:45:00,21410.00,21312.00
15,01/01/2024 01:45:00 - 01/01/2024 02:00:00,21012.00,21044.00
16,01/01/2024 02:00:00 - 01/01/2024 02:15:00,20525.00,20748.00
17,01/01/2024 02:15:00 - 01/01/2024 02:30:00,20113.00,20416.00
18,01/01/2024 02:30:00 - 01/01/2024 02:45:00,19766.00,20144.00
19,01/01/2024 02:45:00 - 01/01/2024 03:00:00,19479.00,19836.00
20,01/01/2024 03:00:00 - 01/01/2024 03:15:00,19202.00,19520.00
21,01/01/2024 03:15:00 - 01/01/2024 03:30:00,18976.00,19192.00
22,01/01/2024 03:30:00 - 01/01/2024 03:45:00,18757.00,18900.00
23,01/01/2024 03:45:00 - 01/01/2024 04:00:00,18548.00,18684.00
24,01/01/2024 04:00:00 - 01/01/2024 04:15:00,18301.00,18500.00
25,01/01/2024 04:15:00 - 01/01/2024 04:30:00,18140.00,18336.00
26,01/01/2024 04:30:00 - 01/01/2024 04:45:00,18013.00,18172.00
27,01/01/2024 04:45:00 - 01/01/2024 05:00:00,17927.00,18036.00
28,01/01/2024 05:00:00 - 01/01/2024 05:15:00,17792.00,17908.00
29,01/01/2024 05:15:00 - 01/01/2024 05:30:00,17797.00,17948.00
30,01/01/2024 05:30:00 - 01/01/2024 05:45:00,17850.00,17888.00
31,01/01/2024 05:45:00 - 01/01/2024 06:00:00,17941.00,17852.00
32,01/01/2024 06:00:00 - 01/01/2024 06:15:00,18044.00,17824.00
33,01/01/2024 06:15:00 - 01/01/2024 06:30:00,18177.00,17988.00
34,01/01/2024 06:30:00 - 01/01/2024 06:45:00,18311.00,18048.00
35,01/01/2024 06:45:00 - 01/01/2024 07:00:00,18435.00,18108.00
36,01/01/2024 07:00:00 - 01/01/2024 07:15:00,18606.00,18176.00
37,01/01/2024 07:15:00 - 01/01/2024 07:30:00,18673.00,18344.00
38,01/01/2024 07:30:00 - 01/01/2024 07:45:00,18698.00,18420.00
39,01/01/2024 07:45:00 - 01/01/2024 08:00:00,18701.00,18512.00
40,01/01/2024 08:00:00 - 01/01/2024 08:15:00,18643.00,18552.00
41,01/01/2024 08:15:00 - 01/01/2024 08:30:00,18672.00,18548.00
42,01/01/2024 08:30:00 - 01/01/2024 08:45:00,18747.00,18464.00
43,01/01/2024 08:45:00 - 01/01/2024 09:00:00,18862.00,18344.00
44,01/01/2024 09:00:00 - 01/01/2024 09:15:00,18972.00,18312.00
45,01/01/2024 09:15:00 - 01/01/2024 09:30:00,19140.00,18504.00
46,01/01/2024 09:30:00 - 01/01/2024 09:45:00,19321.00,18712.00
47,01/01/2024 09:45:00 - 01/01/2024 10:00:00,19511.00,18856.00
48,01/01/2024 10:00:00 - 01/01/2024 10:15:00,19712.00,19028.00
49,01/01/2024 10:15:00 - 01/01/2024 10:30:00,19911.00,19220.00

In [39]:
df_gen.head(50)

,Actual Generation per Production Type - Generation,Unnamed: 1,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7,Unnamed: 8,Unnamed: 9,...,Unnamed: 12,Unnamed: 13,Unnamed: 14,Unnamed: 15,Unnamed: 16,Unnamed: 17,Unnamed: 18,Unnamed: 19,Unnamed: 20,Unnamed: 21
0,Aggregated Generation per Type [16.1.B&C],NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,01/01/2024 00:00 - 01/01/2025 00:00 (CET/CEST),NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,MTU,BZN|ES,BZN|ES,BZN|ES,BZN|ES,BZN|ES,BZN|ES,BZN|ES,BZN|ES,BZN|ES,...,BZN|ES,BZN|ES,BZN|ES,BZN|ES,BZN|ES,BZN|ES,BZN|ES,BZN|ES,BZN|ES,BZN|ES
4,MTU,Biomass (MW),Fossil Brown coal/Lignite (MW),Fossil Coal-derived gas (MW),Fossil Gas (MW),Fossil Hard coal (MW),Fossil Oil (MW),Fossil Oil shale (MW),Fossil Peat (MW),Geothermal (MW),...,Hydro Water Reservoir (MW),Marine (MW),Nuclear (MW),Other renewable (MW),Solar (MW),Waste (MW),Wind Offshore (MW),Wind Onshore (MW),Other (MW),Energy storage (MW)
5,01/01/2024 00:00:00 - 01/01/2024 00:15:00,244.00,0.00,0.00,4552.00,280.00,24.00,0.00,0.00,0.00,...,2544.00,0.00,7096.00,76.00,28.00,240.00,0.00,5376.00,0.00,n/e
6,01/01/2024 00:15:00 - 01/01/2024 00:30:00,244.00,0.00,0.00,4452.00,280.00,20.00,0.00,0.00,0.00,...,2160.00,0.00,7096.00,76.00,28.00,240.00,0.00,5380.00,0.00,n/e
7,01/01/2024 00:30:00 - 01/01/2024 00:45:00,252.00,0.00,0.00,4428.00,280.00,20.00,0.00,0.00,0.00,...,2144.00,0.00,7096.00,76.00,28.00,244.00,0.00,5536.00,0.00,n/e
8,01/01/2024 00:45:00 - 01/01/2024 01:00:00,248.00,0.00,0.00,4316.00,280.00,20.00,0.00,0.00,0.00,...,2104.00,0.00,7096.00,76.00,28.00,248.00,0.00,5624.00,0.00,n/e
9,01/01/2024 01:00:00 - 01/01/2024 01:15:00,244.00,0.00,0.00,4268.00,280.00,20.00,0.00,0.00,0.00,...,2000.00,0.00,7096.00,76.00,28.00,248.00,0.00,5632.00,0.00,n/e
10,01/01/2024 01:15:00 - 01/01/2024 01:30:00,240.00,0.00,0.00,4380.00,276.00,20.00,0.00,0.00,0.00,...,2052.00,0.00,7096.00,76.00,28.00,248.00,0.00,5664.00,0.00,n/e
11,01/01/2024 01:30:00 - 01/01/2024 01:45:00,228.00,0.00,0.00,4404.00,272.00,20.00,0.00,0.00,0.00,...,2044.00,0.00,7096.00,72.00,28.00,244.00,0.00,5672.00,0.00,n/e
12,01/01/2024 01:45:00 - 01/01/2024 02:00:00,228.00,0.00,0.00,4272.00,272.00,20.00,0.00,0.00,0.00,...,1948.00,0.00,7096.00,72.00,28.00,248.00,0.00,5656.00,0.00,n/e
13,01/01/2024 02:00:00 - 01/01/2024 02:15:00,228.00,0.00,0.00,4104.00,272.00,20.00,0.00,0.00,0.00,...,1824.00,0.00,7096.00,72.00,28.00,248.00,0.00,5608.00,0.00,n/e
14,01/01/2024 02:15:00 - 01/01/2024 02:30:00,220.00,0.00,0.00,4312.00,272.00,20.00,0.00,0.00,0.00,...,1884.00,0.00,7096.00,72.00,28.00,248.00,0.00,5612.00,0.00,n/e
15,01/01/2024 02:30:00 - 01/01/2024 02:45:00,220.00,0.00,0.00,4456.00,272.00,20.00,0.00,0.00,0.00,...,1952.00,0.00,7096.00,72.00,28.00,244.00,0.00,5544.00,0.00,n/e
16,01/01/2024 02:45:00 - 01/01/2024 03:00:00,216.00,0.00,0.00,4432.00,272.00,20.00,0.00,0.00,0.00,...,1924.00,0.00,7096.00,72.00,28.00,248.00,0.00,5448.00,0.00,n/e
17,01/01/2024 03:00:00 - 01/01/2024 03:15:00,216.00,0.00,0.00,4452.00,272.00,20.00,0.00,0.00,0.00,...,1852.00,0.00,7096.00,72.00,28.00,244.00,0.00,5240.00,0.00,n/e
18,01/01/2024 03:15:00 - 01/01/2024 03:30:00,208.00,0.00,0.00,4520.00,272.00,20.00,0.00,0.00,0.00,...,1728.00,0.00,7096.00,76.00,28.00,240.00,0.00,5200.00,0.00,n/e
19,01/01/2024 03:30:00 - 01/01/2024 03:45:00,216.00,0.00,0.00,4540.00,272.00,20.00,0.00,0.00,0.00,...,1612.00,0.00,7096.00,76.00,28.00,244.00,0.00,5240.00,0.00,n/e
20,01/01/2024 03:45:00 - 01/01/2024 04:00:00,216.00,0.00,0.00,4396.00,272.00,20.00,0.00,0.00,0.00,...,1552.00,0.00,7096.00,72.00,28.00,244.00,0.00,5240.00,0.00,n/e
21,01/01/2024 04:00:00 - 01/01/2024 04:15:00,220.00,0.00,0.00,4308.00,272.00,20.00,0.00,0.00,0.00,...,1440.00,0.00,7096.00,72.00,28.00,244.00,0.00,5212.00,0.00,n/e
22,01/01/2024 04:15:00 - 01/01/2024 04:30:00,220.00,0.00,0.00,4408.00,272.00,20.00,0.00,0.00,0.00,...,1524.00,0.00,7096.00,76.00,28.00,244.00,0.00,5260.00,0.00,n/e
23,01/01/2024 04:30:00 - 01/01/2024 04:45:00,220.00,0.00,0.00,4492.00,272.00,20.00,0.00,0.00,0.00,...,1604.00,0.00,7096.00,72.00,28.00,248.00,0.00,5256.00,0.00,n/e
24,01/01/2024 04:45:00 - 01/01/2024 05:00:00,216.00,0.00,0.00,4544.00,272.00,20.00,0.00,0.00,0.00,...,1592.00,0.00,7096.00,72.00,28.00,248.00,0.00,5204.00,0.00,n/e
25,01/01/2024 05:00:00 - 01/01/2024 05:15:00,212.00,0.00,0.00,4604.00,272.00,20.00,0.00,0.00,0.00,...,1412.00,0.00,7092.00,76.00,28.00,248.00,0.00,5132.00,0.00,n/e
26,01/01/2024 05:15:00 - 01/01/2024 05:30:00,212.00,0.00,0.00,4688.00,272.00,20.00,0.00,0.00,0.00,...,1360.00,0.00,7092.00,72.00,28.00,248.00,0.00,5164.00,0.00,n/e
27,01/01/2024 05:30:00 - 01/01/2024 05:45:00,212.00,0.00,0.00,4744.00,272.00,20.00,0.00,0.00,0.00,...,1312.00,0.00,7092.00,72.00,28.00,248.00,0.00,5192.00,0.00,n/e
28,01/01/2024 05:45:00 - 01/01/2024 06:00:00,212.00,0.00,0.00,4704.00,272.00,20.00,0.00,0.00,0.00,...,1288.00,0.00,7092.00,72.00,28.00,248.00,0.00,5196.00,0.00,n/e
29,01/01/2024 06:00:00 - 01/01/2024 06:15:00,212.00,0.00,0.00,4676.00,272.00,20.00,0.00,0.00,0.00,...,1272.00,0.00,7092.00,76.00,28.00,248.00,0.00,5232.00,0.00,n/e
30,01/01/2024 06:15:00 - 01/01/2024 06:30:00,212.00,0.00,0.00,4628.00,272.00,20.00,0.00,0.00,0.00,...,1272.00,0.00,7092.00,72.00,28.00,248.00,0.00,5220.00,0.00,n/e
31,01/01/2024 06:30:00 - 01/01/2024 06:45:00,212.00,0.00,0.00,4660.00,272.00,20.00,0.00,0.00,0.00,...,1292.00,0.00,7092.00,72.00,28.00,244.00,0.00,5204.00,0.00,n/e
32,01/01/2024 06:45:00 - 01/01/2024 07:00:00,220.00,0.00,0.00,4580.00,272.00,20.00,0.00,0.00,0.00,...,1376.00,0.00,7092.00,72.00,28.00,244.00,0.00,5244.00,0.00,n/e
33,01/01/2024 07:00:00 - 01/01/2024 07:15:00,220.00,0.00,0.00,4532.00,272.00,20.00,0.00,0.00,0.00,...,1588.00,0.00,7092.00,72.00,28.00,240.00,0.00,5324.00,0.00,n/e
34,01/01/2024 07:15:00 - 01/01/2024 07:30:00,216.00,0.00,0.00,4576.00,272.00,20.00,0.00,0.00,0.00,...,1712.00,0.00,7092.00,72.00,28.00,244.00,0.00,5296.00,0.00,n/e
35,01/01/2024 07:30:00 - 01/01/2024 07:45:00,216.00,0.00,0.00,4620.00,272.00,20.00,0.00,0.00,0.00,...,1728.00,0.00,7092.00,72.00,28.00,244.00,0.00,5384.00,0.00,n/e
36,01/01/2024 07:45:00 - 01/01/2024 08:00:00,216.00,0.00,0.00,4496.00,272.00,20.00,0.00,0.00,0.00,...,1704.00,0.00,7092.00,72.00,28.00,244.00,0.00,5520.00,0.00,n/e
37,01/01/2024 08:00:00 - 01/01/2024 08:15:00,212.00,0.00,0.00,4600.00,272.00,20.00,0.00,0.00,0.00,...,1728.00,0.00,7092.00,72.00,28.00,244.00,0.00,5552.00,0.00,n/e
38,01/01/2024 08:15:00 - 01/01/2024 08:30:00,208.00,0.00,0.00,4528.00,272.00,20.00,0.00,0.00,0.00,...,1708.00,0.00,7092.00,72.00,32.00,244.00,0.00,5608.00,0.00,n/e
39,01/01/2024 08:30:00 - 01/01/2024 08:45:00,212.00,0.00,0.00,4452.00,272.00,20.00,0.00,0.00,0.00,...,1732.00,0.00,7092.00,72.00,32.00,244.00,0.00,5616.00,0.00,n/e
40,01/01/2024 08:45:00 - 01/01/2024 09:00:00,212.00,0.00,0.00,4420.00,272.00,20.00,0.00,0.00,0.00,...,1648.00,0.00,7092.00,72.00,44.00,244.00,0.00,5680.00,0.00,n/e
41,01/01/2024 09:00:00 - 01/01/2024 09:15:00,216.00,0.00,0.00,4644.00,272.00,20.00,0.00,0.00,0.00,...,1728.00,0.00,7092.00,72.00,100.00,244.00,0.00,5776.00,0.00,n/e
42,01/01/2024 09:15:00 - 01/01/2024 09:30:00,216.00,0.00,0.00,4852.00,272.00,20.00,0.00,0.00,0.00,...,1676.00,0.00,7092.00,72.00,320.00,244.00,0.00,5932.00,0.00,n/e
43,01/01/2024 09:30:00 - 01/01/2024 09:45:00,216.00,0.00,0.00,5032.00,272.00,20.00,0.00,0.00,0.00,...,1620.00,0.00,7092.00,72.00,764.00,244.00,0.00,5868.00,0.00,n/e
44,01/01/2024 09:45:00 - 01/01/2024 10:00:00,216.00,0.00,0.00,4940.00,272.00,20.00,0.00,0.00,0.00,...,1560.00,0.00,7092.00,72.00,1444.00,244.00,0.00,5820.00,0.00,n/e
45,01/01/2024 10:00:00 - 01/01/2024 10:15:00,216.00,0.00,0.00,4560.00,272.00,20.00,0.00,0.00,0.00,...,1356.00,0.00,7092.00,72.00,2208.00,244.00,0.00,5824.00,0.00,n/e
46,01/01/2024 10:15:00 - 01/01/2024 10:30:00,212.00,0.00,0.00,3968.00,272.00,20.00,0.00,0.00,0.00,...,1352.00,0.00,7092.00,72.00,2988.00,240.00,0.00,5800.00,0.00,n/e
47,01/01/2024 10:30:00 - 01/01/2024 10:45:00,208.00,0.00,0.00,3820.00,272.00,20.00,0.00,0.00,0.00,...,1468.00,0.00,7092.00,68.00,3668.00,240.00,0.00,5788.00,0.00,n/e
48,01/01/2024 10:45:00 - 01/01/2024 11:00:00,212.00,0.00,0.00,3644.00,272.00,20.00,0.00,0.00,0.00,...,1388.00,0.00,7092.00,68.00,4968.00,240.00,0.00,5780.00,0.00,n/e
49,01/01/2024 11:00:00 - 01/01/2024 11:15:00,216.00,0.00,0.00,3344.00,272.00,20.00,0.00,0.00,0.00,...,1248.00,0.00,7092.00,68.00,5792.00,240.00,0.00,5664.00,0.00,n/e