In [3]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [5]:
# Read the data into a Pandas DataFrame

input_gen = "/Users/mac/Desktop/ RED/Data Final Project/AGGREGATED_GENERATION_PER_TYPE_GENERATION_202312312300-202412312300.csv"  # Load the Excel file
input_price = "/Users/mac/Desktop/ RED/Data Final Project/GUI_ENERGY_PRICES_202412222300-202412232300.csv"  # Load the Excel file
input_load = "/Users/mac/Desktop/ RED/Data Final Project/GUI_TOTAL_LOAD_DAYAHEAD_202312312300-202412312300.csv"  # Load the Excel file

df_gen= pd.read_csv(input_gen)  
df_price= pd.read_csv(input_price)
df_load= pd.read_csv(input_load)

In [9]:
df_load.head(50)

,"""MTU""",AREA,Day ahead total load forecast (MW),Actual total load (MW)
0,"""01/01/2024 00:00:00 - 01/01/2024 00:15:00""",BZN|ES,21981.00,22460.00
1,"""01/01/2024 00:15:00 - 01/01/2024 00:30:00""",BZN|ES,21863.00,22060.00
2,"""01/01/2024 00:30:00 - 01/01/2024 00:45:00""",BZN|ES,21807.00,21880.00
3,"""01/01/2024 00:45:00 - 01/01/2024 01:00:00""",BZN|ES,21767.00,21788.00
4,"""01/01/2024 01:00:00 - 01/01/2024 01:15:00""",BZN|ES,21890.00,21648.00
5,"""01/01/2024 01:15:00 - 01/01/2024 01:30:00""",BZN|ES,21715.00,21508.00
6,"""01/01/2024 01:30:00 - 01/01/2024 01:45:00""",BZN|ES,21410.00,21312.00
7,"""01/01/2024 01:45:00 - 01/01/2024 02:00:00""",BZN|ES,21012.00,21044.00
8,"""01/01/2024 02:00:00 - 01/01/2024 02:15:00""",BZN|ES,20525.00,20748.00
9,"""01/01/2024 02:15:00 - 01/01/2024 02:30:00""",BZN|ES,20113.00,20416.00
10,"""01/01/2024 02:30:00 - 01/01/2024 02:45:00""",BZN|ES,19766.00,20144.00
11,"""01/01/2024 02:45:00 - 01/01/2024 03:00:00""",BZN|ES,19479.00,19836.00
12,"""01/01/2024 03:00:00 - 01/01/2024 03:15:00""",BZN|ES,19202.00,19520.00
13,"""01/01/2024 03:15:00 - 01/01/2024 03:30:00""",BZN|ES,18976.00,19192.00
14,"""01/01/2024 03:30:00 - 01/01/2024 03:45:00""",BZN|ES,18757.00,18900.00
15,"""01/01/2024 03:45:00 - 01/01/2024 04:00:00""",BZN|ES,18548.00,18684.00
16,"""01/01/2024 04:00:00 - 01/01/2024 04:15:00""",BZN|ES,18301.00,18500.00
17,"""01/01/2024 04:15:00 - 01/01/2024 04:30:00""",BZN|ES,18140.00,18336.00
18,"""01/01/2024 04:30:00 - 01/01/2024 04:45:00""",BZN|ES,18013.00,18172.00
19,"""01/01/2024 04:45:00 - 01/01/2024 05:00:00""",BZN|ES,17927.00,18036.00
20,"""01/01/2024 05:00:00 - 01/01/2024 05:15:00""",BZN|ES,17792.00,17908.00
21,"""01/01/2024 05:15:00 - 01/01/2024 05:30:00""",BZN|ES,17797.00,17948.00
22,"""01/01/2024 05:30:00 - 01/01/2024 05:45:00""",BZN|ES,17850.00,17888.00
23,"""01/01/2024 05:45:00 - 01/01/2024 06:00:00""",BZN|ES,17941.00,17852.00
24,"""01/01/2024 06:00:00 - 01/01/2024 06:15:00""",BZN|ES,18044.00,17824.00
25,"""01/01/2024 06:15:00 - 01/01/2024 06:30:00""",BZN|ES,18177.00,17988.00
26,"""01/01/2024 06:30:00 - 01/01/2024 06:45:00""",BZN|ES,18311.00,18048.00
27,"""01/01/2024 06:45:00 - 01/01/2024 07:00:00""",BZN|ES,18435.00,18108.00
28,"""01/01/2024 07:00:00 - 01/01/2024 07:15:00""",BZN|ES,18606.00,18176.00
29,"""01/01/2024 07:15:00 - 01/01/2024 07:30:00""",BZN|ES,18673.00,18344.00
30,"""01/01/2024 07:30:00 - 01/01/2024 07:45:00""",BZN|ES,18698.00,18420.00
31,"""01/01/2024 07:45:00 - 01/01/2024 08:00:00""",BZN|ES,18701.00,18512.00
32,"""01/01/2024 08:00:00 - 01/01/2024 08:15:00""",BZN|ES,18643.00,18552.00
33,"""01/01/2024 08:15:00 - 01/01/2024 08:30:00""",BZN|ES,18672.00,18548.00
34,"""01/01/2024 08:30:00 - 01/01/2024 08:45:00""",BZN|ES,18747.00,18464.00
35,"""01/01/2024 08:45:00 - 01/01/2024 09:00:00""",BZN|ES,18862.00,18344.00
36,"""01/01/2024 09:00:00 - 01/01/2024 09:15:00""",BZN|ES,18972.00,18312.00
37,"""01/01/2024 09:15:00 - 01/01/2024 09:30:00""",BZN|ES,19140.00,18504.00
38,"""01/01/2024 09:30:00 - 01/01/2024 09:45:00""",BZN|ES,19321.00,18712.00
39,"""01/01/2024 09:45:00 - 01/01/2024 10:00:00""",BZN|ES,19511.00,18856.00
40,"""01/01/2024 10:00:00 - 01/01/2024 10:15:00""",BZN|ES,19712.00,19028.00
41,"""01/01/2024 10:15:00 - 01/01/2024 10:30:00""",BZN|ES,19911.00,19220.00
42,"""01/01/2024 10:30:00 - 01/01/2024 10:45:00""",BZN|ES,20109.00,19572.00
43,"""01/01/2024 10:45:00 - 01/01/2024 11:00:00""",BZN|ES,20296.00,20372.00
44,"""01/01/2024 11:00:00 - 01/01/2024 11:15:00""",BZN|ES,20525.00,20640.00
45,"""01/01/2024 11:15:00 - 01/01/2024 11:30:00""",BZN|ES,20663.00,20820.00
46,"""01/01/2024 11:30:00 - 01/01/2024 11:45:00""",BZN|ES,20765.00,20992.00
47,"""01/01/2024 11:45:00 - 01/01/2024 12:00:00""",BZN|ES,20844.00,21128.00
48,"""01/01/2024 12:00:00 - 01/01/2024 12:15:00""",BZN|ES,20886.00,21136.00
49,"""01/01/2024 12:15:00 - 01/01/2024 12:30:00""",BZN|ES,20972.00,21168.00

In [11]:
df_gen.head(50)

,MTU (CET/CEST),Area,Production Type,Generation (MW)
0,01/01/2024 00:00:00 - 01/01/2024 00:15:00,BZN|ES,Biomass,244.00
1,01/01/2024 00:00:00 - 01/01/2024 00:15:00,BZN|ES,Fossil Brown coal/Lignite,0.00
2,01/01/2024 00:00:00 - 01/01/2024 00:15:00,BZN|ES,Fossil Coal-derived gas,0.00
3,01/01/2024 00:00:00 - 01/01/2024 00:15:00,BZN|ES,Fossil Gas,4552.00
4,01/01/2024 00:00:00 - 01/01/2024 00:15:00,BZN|ES,Fossil Hard coal,280.00
5,01/01/2024 00:00:00 - 01/01/2024 00:15:00,BZN|ES,Fossil Oil,24.00
6,01/01/2024 00:00:00 - 01/01/2024 00:15:00,BZN|ES,Fossil Oil shale,0.00
7,01/01/2024 00:00:00 - 01/01/2024 00:15:00,BZN|ES,Fossil Peat,0.00
8,01/01/2024 00:00:00 - 01/01/2024 00:15:00,BZN|ES,Geothermal,0.00
9,01/01/2024 00:00:00 - 01/01/2024 00:15:00,BZN|ES,Hydro Pumped Storage,1548.00
10,01/01/2024 00:00:00 - 01/01/2024 00:15:00,BZN|ES,Hydro Run-of-river and poundage,1016.00
11,01/01/2024 00:00:00 - 01/01/2024 00:15:00,BZN|ES,Hydro Water Reservoir,2544.00
12,01/01/2024 00:00:00 - 01/01/2024 00:15:00,BZN|ES,Marine,0.00
13,01/01/2024 00:00:00 - 01/01/2024 00:15:00,BZN|ES,Nuclear,7096.00
14,01/01/2024 00:00:00 - 01/01/2024 00:15:00,BZN|ES,Other renewable,76.00
15,01/01/2024 00:00:00 - 01/01/2024 00:15:00,BZN|ES,Solar,28.00
16,01/01/2024 00:00:00 - 01/01/2024 00:15:00,BZN|ES,Waste,240.00
17,01/01/2024 00:00:00 - 01/01/2024 00:15:00,BZN|ES,Wind Offshore,0.00
18,01/01/2024 00:00:00 - 01/01/2024 00:15:00,BZN|ES,Wind Onshore,5376.00
19,01/01/2024 00:00:00 - 01/01/2024 00:15:00,BZN|ES,Other,0.00
20,01/01/2024 00:00:00 - 01/01/2024 00:15:00,BZN|ES,Energy storage,n/e
21,01/01/2024 00:15:00 - 01/01/2024 00:30:00,BZN|ES,Biomass,244.00
22,01/01/2024 00:15:00 - 01/01/2024 00:30:00,BZN|ES,Fossil Brown coal/Lignite,0.00
23,01/01/2024 00:15:00 - 01/01/2024 00:30:00,BZN|ES,Fossil Coal-derived gas,0.00
24,01/01/2024 00:15:00 - 01/01/2024 00:30:00,BZN|ES,Fossil Gas,4452.00
25,01/01/2024 00:15:00 - 01/01/2024 00:30:00,BZN|ES,Fossil Hard coal,280.00
26,01/01/2024 00:15:00 - 01/01/2024 00:30:00,BZN|ES,Fossil Oil,20.00
27,01/01/2024 00:15:00 - 01/01/2024 00:30:00,BZN|ES,Fossil Oil shale,0.00
28,01/01/2024 00:15:00 - 01/01/2024 00:30:00,BZN|ES,Fossil Peat,0.00
29,01/01/2024 00:15:00 - 01/01/2024 00:30:00,BZN|ES,Geothermal,0.00
30,01/01/2024 00:15:00 - 01/01/2024 00:30:00,BZN|ES,Hydro Pumped Storage,1372.00
31,01/01/2024 00:15:00 - 01/01/2024 00:30:00,BZN|ES,Hydro Run-of-river and poundage,1004.00
32,01/01/2024 00:15:00 - 01/01/2024 00:30:00,BZN|ES,Hydro Water Reservoir,2160.00
33,01/01/2024 00:15:00 - 01/01/2024 00:30:00,BZN|ES,Marine,0.00
34,01/01/2024 00:15:00 - 01/01/2024 00:30:00,BZN|ES,Nuclear,7096.00
35,01/01/2024 00:15:00 - 01/01/2024 00:30:00,BZN|ES,Other renewable,76.00
36,01/01/2024 00:15:00 - 01/01/2024 00:30:00,BZN|ES,Solar,28.00
37,01/01/2024 00:15:00 - 01/01/2024 00:30:00,BZN|ES,Waste,240.00
38,01/01/2024 00:15:00 - 01/01/2024 00:30:00,BZN|ES,Wind Offshore,0.00
39,01/01/2024 00:15:00 - 01/01/2024 00:30:00,BZN|ES,Wind Onshore,5380.00
40,01/01/2024 00:15:00 - 01/01/2024 00:30:00,BZN|ES,Other,0.00
41,01/01/2024 00:15:00 - 01/01/2024 00:30:00,BZN|ES,Energy storage,n/e
42,01/01/2024 00:30:00 - 01/01/2024 00:45:00,BZN|ES,Biomass,252.00
43,01/01/2024 00:30:00 - 01/01/2024 00:45:00,BZN|ES,Fossil Brown coal/Lignite,0.00
44,01/01/2024 00:30:00 - 01/01/2024 00:45:00,BZN|ES,Fossil Coal-derived gas,0.00
45,01/01/2024 00:30:00 - 01/01/2024 00:45:00,BZN|ES,Fossil Gas,4428.00
46,01/01/2024 00:30:00 - 01/01/2024 00:45:00,BZN|ES,Fossil Hard coal,280.00
47,01/01/2024 00:30:00 - 01/01/2024 00:45:00,BZN|ES,Fossil Oil,20.00
48,01/01/2024 00:30:00 - 01/01/2024 00:45:00,BZN|ES,Fossil Oil shale,0.00
49,01/01/2024 00:30:00 - 01/01/2024 00:45:00,BZN|ES,Fossil Peat,0.00

In [13]:
df_price.head(50)

,MTU (CET/CEST),Area,Sequence,Day-ahead (EUR/MWh),Intraday Period (CET/CEST),Energy Price (EUR/MWh)
0,23/12/2024 00:00:00 - 23/12/2024 01:00:00,BZN|ES,Without sequence,17.27,NaN,NaN
1,23/12/2024 01:00:00 - 23/12/2024 02:00:00,BZN|ES,Without sequence,11.48,NaN,NaN
2,23/12/2024 02:00:00 - 23/12/2024 03:00:00,BZN|ES,Without sequence,10.19,NaN,NaN
3,23/12/2024 03:00:00 - 23/12/2024 04:00:00,BZN|ES,Without sequence,7.33,NaN,NaN
4,23/12/2024 04:00:00 - 23/12/2024 05:00:00,BZN|ES,Without sequence,6.00,NaN,NaN
5,23/12/2024 05:00:00 - 23/12/2024 06:00:00,BZN|ES,Without sequence,7.07,NaN,NaN
6,23/12/2024 06:00:00 - 23/12/2024 07:00:00,BZN|ES,Without sequence,25.95,NaN,NaN
7,23/12/2024 07:00:00 - 23/12/2024 08:00:00,BZN|ES,Without sequence,61.20,NaN,NaN
8,23/12/2024 08:00:00 - 23/12/2024 09:00:00,BZN|ES,Without sequence,72.47,NaN,NaN
9,23/12/2024 09:00:00 - 23/12/2024 10:00:00,BZN|ES,Without sequence,70.93,NaN,NaN
10,23/12/2024 10:00:00 - 23/12/2024 11:00:00,BZN|ES,Without sequence,25.00,NaN,NaN
11,23/12/2024 11:00:00 - 23/12/2024 12:00:00,BZN|ES,Without sequence,5.11,NaN,NaN
12,23/12/2024 12:00:00 - 23/12/2024 13:00:00,BZN|ES,Without sequence,3.32,NaN,NaN
13,23/12/2024 13:00:00 - 23/12/2024 14:00:00,BZN|ES,Without sequence,3.32,NaN,NaN
14,23/12/2024 14:00:00 - 23/12/2024 15:00:00,BZN|ES,Without sequence,3.60,NaN,NaN
15,23/12/2024 15:00:00 - 23/12/2024 16:00:00,BZN|ES,Without sequence,5.00,NaN,NaN
16,23/12/2024 16:00:00 - 23/12/2024 17:00:00,BZN|ES,Without sequence,30.90,NaN,NaN
17,23/12/2024 17:00:00 - 23/12/2024 18:00:00,BZN|ES,Without sequence,87.11,NaN,NaN
18,23/12/2024 18:00:00 - 23/12/2024 19:00:00,BZN|ES,Without sequence,114.72,NaN,NaN
19,23/12/2024 19:00:00 - 23/12/2024 20:00:00,BZN|ES,Without sequence,124.89,NaN,NaN
20,23/12/2024 20:00:00 - 23/12/2024 21:00:00,BZN|ES,Without sequence,118.97,NaN,NaN
21,23/12/2024 21:00:00 - 23/12/2024 22:00:00,BZN|ES,Without sequence,109.28,NaN,NaN
22,23/12/2024 22:00:00 - 23/12/2024 23:00:00,BZN|ES,Without sequence,105.82,NaN,NaN
23,23/12/2024 23:00:00 - 24/12/2024 00:00:00,BZN|ES,Without sequence,90.80,NaN,NaN